The error `ModuleNotFoundError: No module named 'requests'` suggests that somewhere in the codebase, there is an import statement for the `requests` module, which is not part of the standard library and is not installed in the environment. However, since the task is to fix the error without introducing new dependencies, we need to ensure that the code does not rely on `requests` or any other non-standard library.

Given the content of the file you provided, there is no direct reference to `requests`. Therefore, the error must be coming from another part of the codebase. However, since you asked for the updated content of this specific file, and assuming the rest of the codebase has been adjusted to not use `requests`, the content of this file remains unchanged as it does not directly relate to the error.

```python
"""init books table

Revision ID: ecc89a33e6cd
Revises: 
Create Date: 2025-12-10 16:50:52.500981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID


# revision identifiers, used by Alembic.
revision = 'ecc89a33e6cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS \"pgcrypto\";")
    op.create_table('books',
    sa.Column('id', PG_UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()"), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
```

Please ensure that any other part of the codebase that might be importing `requests` is modified to not require it, or that the functionality is replaced with a standard library equivalent. If you need further assistance with other parts of the codebase, please provide additional context or files.